/**
 * CinePik Recommendation Engine API
 * The Recommendation Engine microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieResponseDto { 
    /**
     * Movie identifier.
     */
    id: number;
    /**
     * Url for the backdrop image.
     */
    backdrop_path: string;
    /**
     * List of genres that best describe the content.
     */
    genres: Array<string>;
    /**
     * Title in the original language.
     */
    original_title: string;
    /**
     * Short movie description.
     */
    overview: string;
    /**
     * Url for the poster image.
     */
    poster_path: string;
    /**
     * Movie release date.
     */
    release_date: string;
    /**
     * Movie title.
     */
    title: string;
    /**
     * Movie vote average.
     */
    vote_average: number;
    /**
     * Recommendations match score.
     */
    match_score: number;
}

