/**
 * CinePik Recommendation Engine API
 * The Recommendation Engine microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShowResponseDto { 
    /**
     * Show identifier.
     */
    id: number;
    /**
     * Url for the backdrop image.
     */
    backdrop_path: string;
    /**
     * List of genres that best describe the content.
     */
    original_title: string;
    /**
     * Short show description.
     */
    poster_path: string;
    /**
     * Show first aired date.
     */
    first_aired: string;
    /**
     * Show title.
     */
    title: string;
    /**
     * Show vote average.
     */
    vote_average: number;
    /**
     * Recommendations match score.
     */
    match_score: number;
}

