/**
 * CinePik Catalog API
 * The CinePik Catalog microservice.
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HomeResponseDto } from '../model/models';
import { SearchResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CommonServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Home
     * The home endpoint offers a curated and dynamic homepage experience, delivering a rich selection of movies categorized to cater to diverse interests and preferences. Users can discover an array of films thoughtfully organized into genres, themes, and trending topics, ensuring they find the perfect cinematic experience tailored to their tastes.
     */
    commonControllerHome(extraHttpRequestParams?: any): Observable<HomeResponseDto>;

    /**
     * Search
     * The Search endpoint empowers users to conduct customized searches, enabling them to discover movies and TV shows based on specific criteria such as genre, actor, director, or keyword, providing a tailored and efficient content discovery experience.
     * @param query 
     */
    commonControllerSearch(query: string, extraHttpRequestParams?: any): Observable<SearchResponseDto>;

}
