/**
 * CinePik Catalog API
 * The CinePik Catalog microservice.
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Info
     * Returns current project version.
     */
    appControllerInfo(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns the Prometheus metrics
     * Returns the Prometheus metrics.
     */
    metricsControllerGetMetrics(extraHttpRequestParams?: any): Observable<string>;

}
