/**
 * CinePik Catalog API
 * The CinePik Catalog microservice.
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MovieDetailWrapperResponseDto } from '../model/models';
import { MovieResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MoviesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns all movies
     * Returns all movies in the database.
     */
    moviesControllerFindAll(extraHttpRequestParams?: any): Observable<Array<MovieResponseDto>>;

    /**
     * Returns a movie
     * Returns a specific movie with an id.
     * @param id 
     */
    moviesControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<MovieDetailWrapperResponseDto>;

}
