/**
 * CinePik Catalog API
 * The CinePik Catalog microservice.
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ShowDetailWrapperResponseDto } from '../model/models';
import { ShowResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShowsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns all shows
     * Returns all shows in the database.
     */
    showsControllerFindAll(extraHttpRequestParams?: any): Observable<Array<ShowResponseDto>>;

    /**
     * Returns a show
     * Returns specific show with an id.
     * @param id 
     */
    showsControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<Array<ShowDetailWrapperResponseDto>>;

}
