/**
 * CinePik Watchlist API
 * The CinePik Watchlist microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HealthControllerCheckLiveness200Response } from '../model/models';
import { HealthControllerCheckLiveness503Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    healthControllerCheckLiveness(extraHttpRequestParams?: any): Observable<HealthControllerCheckLiveness200Response>;

    /**
     * 
     * 
     */
    healthControllerCheckReadiness(extraHttpRequestParams?: any): Observable<HealthControllerCheckLiveness200Response>;

    /**
     * 
     * 
     */
    healthControllerToggleHealth(extraHttpRequestParams?: any): Observable<{}>;

}
