/**
 * CinePik Recommendation Engine API
 * The Recommendation Engine microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MovieResponseDto } from '../model/models';
import { ShowResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RecommendationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns recommended movies
     * Returns recommended movies depending on the provided movie ids.
     * @param movieIds 
     */
    recommendationsControllerGetMovieRecommendations(movieIds: Array<string>, extraHttpRequestParams?: any): Observable<Array<MovieResponseDto>>;

    /**
     * Returns recommended shows
     * Returns recommended shows depending on the provided show ids.
     * @param showIds 
     */
    recommendationsControllerGetShowRecommendations(showIds: Array<string>, extraHttpRequestParams?: any): Observable<Array<ShowResponseDto>>;

}
