/**
 * CinePik Catalog API
 * The CinePik Catalog microservice.
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HomeContentResponseDto } from './homeContentResponseDto';


export interface HomeSectionResponseDto { 
    /**
     * Section title.
     */
    title: string;
    /**
     * A list of section contents (movies and shows).
     */
    content: Array<HomeContentResponseDto>;
}

