/**
 * CinePik Catalog API
 * The CinePik Catalog microservice.
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HomeSectionResponseDto } from './homeSectionResponseDto';


export interface HomeResponseDto { 
    /**
     * A list of content sections.
     */
    sections: Array<HomeSectionResponseDto>;
}

