/**
 * CinePik Watchlist API
 * The CinePik Watchlist microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateMovieCommentDto { 
    /**
     * User identifier.
     */
    userId: number;
    /**
     * Movie identifier.
     */
    movieId: number;
    /**
     * Movie rating.
     */
    rating: number;
    /**
     * User comment.
     */
    comment: string;
}

