/**
 * CinePik Watchlist API
 * The CinePik Watchlist microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieCommentResponseDto { 
    /**
     * Comment identifier.
     */
    id: number;
    /**
     * User identifier.
     */
    userId: string;
    /**
     * Cinepik movie identifier.
     */
    movieId: number;
    /**
     * Movie rating.
     */
    rating: number;
    /**
     * User comment.
     */
    comment: string;
    /**
     * Movie creation date.
     */
    createdAt: string;
    /**
     * Movie update date.
     */
    updatedAt: string;
}

