/**
 * CinePik Watchlist API
 * The CinePik Watchlist microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShowCommentResponseDto { 
    /**
     * Comment identifier.
     */
    id: number;
    /**
     * User identifier.
     */
    userId: number;
    /**
     * Show identifier.
     */
    showId: number;
    /**
     * Show episode.
     */
    episode: number;
    /**
     * Show season.
     */
    season: number;
    /**
     * Show rating.
     */
    rating: number;
    /**
     * User comment.
     */
    comment: string;
    /**
     * Has the user watched the show.
     */
    watched: boolean;
    /**
     * Show creation date.
     */
    createdAt: string;
    /**
     * Show update date.
     */
    updatedAt: string;
}

