/**
 * CinePik Watchlist API
 * The CinePik Watchlist microservice.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatformResponseDto } from './platformResponseDto';


export interface SourceResponseDto { 
    /**
     * Source name.
     */
    source: string;
    /**
     * Source content link.
     */
    link: string;
    /**
     * Source type.
     */
    type: string;
    /**
     * Source name to be displayed.
     */
    display_name: string;
    /**
     * Source info url.
     */
    info: string;
    /**
     * Source logo url.
     */
    logo_url: string;
    /**
     * Source platforms.
     */
    platform: Array<PlatformResponseDto>;
}

